# Multi-Station Data Retrieval

In this example, we will retrieve multi-station data for the past 30 days from a list of stations:['KLAX', 'KONT', 'KRAL', 'KRIV']

We will then create CSV files of this data and then open that data in Pandas.

## Imports

In [1]:
import pandas as pd
from xmacis2py import get_multi_station_data

In [2]:
# Define our list of station IDs
stations = ['KLAX', 'KONT', 'KRAL', 'KRIV']

## Retrieving The Data With xmACIS2Py

In this example, we want to create CSV files for each station.

To do this we must change our optional argument of `to_csv=True` and in this case it is good practice to set `return_pandas_df=False`

The default path for the CSV files to save is f:XMACIS DATA/{files}

In [3]:
get_multi_station_data(['KLAX', 'KONT', 'KRAL', 'KRIV'],
                      to_csv=True,
                      return_pandas_df=False)

KLAX Data Saved: XMACIS2 DATA/KLAX.csv
KONT Data Saved: XMACIS2 DATA/KONT.csv
KRAL Data Saved: XMACIS2 DATA/KRAL.csv
KRIV Data Saved: XMACIS2 DATA/KRIV.csv

In [4]:
klax = pd.read_csv(f"XMACIS2 DATA/KLAX.csv")

In [5]:
klax

,Date,Maximum Temperature,Minimum Temperature,Average Temperature,Average Temperature Departure,Heating Degree Days,Cooling Degree Days,Precipitation,Snowfall,Snow Depth,Growing Degree Days
0,2026-03-20,85,63,74.0,14.6,0,9,0.000,NaN,NaN,24
1,2026-03-21,74,60,67.0,7.6,0,2,0.000,NaN,NaN,17
2,2026-03-22,70,60,65.0,5.5,0,0,0.000,NaN,NaN,15
3,2026-03-23,71,59,65.0,5.5,0,0,0.000,NaN,NaN,15
4,2026-03-24,70,61,65.5,5.9,0,1,0.000,NaN,NaN,16
5,2026-03-25,68,59,63.5,3.8,1,0,0.000,NaN,NaN,14
6,2026-03-26,73,59,66.0,6.3,0,1,0.000,NaN,NaN,16
7,2026-03-27,71,59,65.0,5.2,0,0,0.000,NaN,NaN,15
8,2026-03-28,68,58,63.0,3.2,2,0,0.000,NaN,NaN,13
9,2026-03-29,73,57,65.0,5.1,0,0,0.000,NaN,NaN,15
10,2026-03-30,70,56,63.0,3.1,2,0,0.000,NaN,NaN,13
11,2026-03-31,69,62,65.5,5.5,0,1,0.070,NaN,NaN,16
12,2026-04-01,68,59,63.5,3.4,1,0,0.040,NaN,NaN,14
13,2026-04-02,68,59,63.5,3.4,1,0,0.000,NaN,NaN,14
14,2026-04-03,78,56,67.0,6.8,0,2,0.000,NaN,NaN,17
15,2026-04-04,87,56,71.5,11.3,0,7,0.000,NaN,NaN,22
16,2026-04-05,78,57,67.5,7.2,0,3,0.000,NaN,NaN,18
17,2026-04-06,78,61,69.5,9.1,0,5,0.000,NaN,NaN,20
18,2026-04-07,70,58,64.0,3.6,1,0,0.000,NaN,NaN,14
19,2026-04-08,71,58,64.5,4.0,0,0,0.000,NaN,NaN,15
20,2026-04-09,72,60,66.0,5.4,0,1,0.000,NaN,NaN,16
21,2026-04-10,67,59,63.0,2.3,2,0,0.000,NaN,NaN,13
22,2026-04-11,69,59,64.0,3.3,1,0,0.001,NaN,NaN,14
23,2026-04-12,69,58,63.5,2.7,1,0,0.160,NaN,NaN,14
24,2026-04-13,66,56,61.0,0.1,4,0,0.000,NaN,NaN,11
25,2026-04-14,69,52,60.5,-0.5,4,0,0.000,NaN,NaN,11
26,2026-04-15,70,55,62.5,1.4,2,0,0.000,NaN,NaN,13
27,2026-04-16,70,56,63.0,1.8,2,0,0.000,NaN,NaN,13
28,2026-04-17,73,56,64.5,3.3,0,0,0.000,NaN,NaN,15
29,2026-04-18,76,58,67.0,5.7,0,2,0.000,NaN,NaN,17
30,2026-04-19,72,59,65.5,4.1,0,1,0.000,NaN,NaN,16

In [6]:
kont = pd.read_csv(f"XMACIS2 DATA/KONT.csv")

In [7]:
kont

,Date,Maximum Temperature,Minimum Temperature,Average Temperature,Average Temperature Departure,Heating Degree Days,Cooling Degree Days,Precipitation,Snowfall,Snow Depth,Growing Degree Days
0,2026-03-20,100,65,82.5,21.9,0,18,0.00,NaN,NaN,33
1,2026-03-21,91,63,77.0,16.3,0,12,0.00,NaN,NaN,27
2,2026-03-22,87,61,74.0,13.2,0,9,0.00,NaN,NaN,24
3,2026-03-23,86,56,71.0,10.1,0,6,0.00,NaN,NaN,21
4,2026-03-24,88,59,73.5,12.5,0,9,0.00,NaN,NaN,24
5,2026-03-25,88,58,73.0,12.0,0,8,0.00,NaN,NaN,23
6,2026-03-26,89,56,72.5,11.4,0,8,0.00,NaN,NaN,23
7,2026-03-27,89,61,75.0,13.8,0,10,0.00,NaN,NaN,25
8,2026-03-28,89,58,73.5,12.2,0,9,0.00,NaN,NaN,24
9,2026-03-29,91,59,75.0,13.7,0,10,0.00,NaN,NaN,25
10,2026-03-30,82,59,70.5,9.1,0,6,0.00,NaN,NaN,21
11,2026-03-31,70,60,65.0,3.5,0,0,0.25,NaN,NaN,15
12,2026-04-01,73,58,65.5,3.9,0,1,0.21,NaN,NaN,16
13,2026-04-02,71,56,63.5,1.8,1,0,0.00,NaN,NaN,14
14,2026-04-03,82,50,66.0,4.2,0,1,0.00,NaN,NaN,16
15,2026-04-04,89,63,76.0,14.1,0,11,0.00,NaN,NaN,26
16,2026-04-05,88,54,71.0,9.0,0,6,0.00,NaN,NaN,21
17,2026-04-06,82,59,70.5,8.4,0,6,0.00,NaN,NaN,21
18,2026-04-07,82,56,69.0,6.8,0,4,0.00,NaN,NaN,19
19,2026-04-08,83,59,71.0,8.7,0,6,0.00,NaN,NaN,21
20,2026-04-09,79,59,69.0,6.6,0,4,0.00,NaN,NaN,19
21,2026-04-10,78,57,67.5,5.0,0,3,0.00,NaN,NaN,18
22,2026-04-11,74,56,65.0,2.3,0,0,0.00,NaN,NaN,15
23,2026-04-12,65,51,58.0,-4.8,7,0,0.33,NaN,NaN,8
24,2026-04-13,66,49,57.5,-5.4,7,0,0.01,NaN,NaN,8
25,2026-04-14,75,49,62.0,-1.1,3,0,0.00,NaN,NaN,12
26,2026-04-15,78,53,65.5,2.3,0,1,0.00,NaN,NaN,16
27,2026-04-16,74,55,64.5,1.1,0,0,0.00,NaN,NaN,15
28,2026-04-17,80,53,66.5,3.0,0,2,0.00,NaN,NaN,17
29,2026-04-18,86,54,70.0,6.3,0,5,0.00,NaN,NaN,20
30,2026-04-19,83,59,71.0,7.2,0,6,0.00,NaN,NaN,21

In [8]:
kral = pd.read_csv(f"XMACIS2 DATA/KRAL.csv")

In [9]:
kral

,Date,Maximum Temperature,Minimum Temperature,Average Temperature,Average Temperature Departure,Heating Degree Days,Cooling Degree Days,Precipitation,Snowfall,Snow Depth,Growing Degree Days
0,2026-03-20,102,63,82.5,22.5,0,18,0.000,NaN,NaN,33
1,2026-03-21,93,61,77.0,16.9,0,12,0.000,NaN,NaN,27
2,2026-03-22,89,58,73.5,13.3,0,9,0.000,NaN,NaN,24
3,2026-03-23,89,56,72.5,12.2,0,8,0.000,NaN,NaN,23
4,2026-03-24,88,58,73.0,12.6,0,8,0.000,NaN,NaN,23
5,2026-03-25,89,57,73.0,12.5,0,8,0.000,NaN,NaN,23
6,2026-03-26,90,55,72.5,11.9,0,8,0.000,NaN,NaN,23
7,2026-03-27,91,59,75.0,14.3,0,10,0.000,NaN,NaN,25
8,2026-03-28,92,55,73.5,12.7,0,9,0.000,NaN,NaN,24
9,2026-03-29,94,58,76.0,15.1,0,11,0.000,NaN,NaN,26
10,2026-03-30,84,54,69.0,8.0,0,4,0.000,NaN,NaN,19
11,2026-03-31,71,59,65.0,3.9,0,0,0.080,NaN,NaN,15
12,2026-04-01,74,54,64.0,2.8,1,0,0.060,NaN,NaN,14
13,2026-04-02,73,54,63.5,2.2,1,0,0.000,NaN,NaN,14
14,2026-04-03,80,51,65.5,4.1,0,1,0.000,NaN,NaN,16
15,2026-04-04,89,54,71.5,10.0,0,7,0.000,NaN,NaN,22
16,2026-04-05,90,53,71.5,9.9,0,7,0.000,NaN,NaN,22
17,2026-04-06,83,60,71.5,9.8,0,7,0.001,NaN,NaN,22
18,2026-04-07,83,53,68.0,6.2,0,3,0.000,NaN,NaN,18
19,2026-04-08,85,56,70.5,8.6,0,6,0.000,NaN,NaN,21
20,2026-04-09,80,57,68.5,6.5,0,4,0.000,NaN,NaN,19
21,2026-04-10,80,58,69.0,6.9,0,4,0.000,NaN,NaN,19
22,2026-04-11,75,57,66.0,3.8,0,1,0.001,NaN,NaN,16
23,2026-04-12,64,52,58.0,-4.4,7,0,0.210,NaN,NaN,8
24,2026-04-13,67,47,57.0,-5.5,8,0,0.020,NaN,NaN,7
25,2026-04-14,75,47,61.0,-1.6,4,0,0.000,NaN,NaN,11
26,2026-04-15,80,50,65.0,2.2,0,0,0.000,NaN,NaN,15
27,2026-04-16,76,53,64.5,1.6,0,0,0.000,NaN,NaN,15
28,2026-04-17,82,52,67.0,4.0,0,2,0.000,NaN,NaN,17
29,2026-04-18,87,46,66.5,3.3,0,2,0.000,NaN,NaN,17
30,2026-04-19,84,57,70.5,7.2,0,6,0.000,NaN,NaN,21

In [10]:
kriv = pd.read_csv(f"XMACIS2 DATA/KRIV.csv")

In [11]:
kriv

,Date,Maximum Temperature,Minimum Temperature,Average Temperature,Average Temperature Departure,Heating Degree Days,Cooling Degree Days,Precipitation,Snowfall,Snow Depth,Growing Degree Days
0,2026-03-20,100,54,77.0,21.0,0,12,0.000,NaN,NaN,27
1,2026-03-21,93,52,72.5,16.4,0,8,0.000,NaN,NaN,23
2,2026-03-22,88,51,69.5,13.4,0,5,0.000,NaN,NaN,20
3,2026-03-23,89,49,69.0,12.8,0,4,0.000,NaN,NaN,19
4,2026-03-24,90,54,72.0,15.7,0,7,0.001,NaN,NaN,22
5,2026-03-25,91,50,70.5,14.2,0,6,0.000,NaN,NaN,21
6,2026-03-26,89,50,69.5,13.1,0,5,0.000,NaN,NaN,20
7,2026-03-27,93,52,72.5,16.1,0,8,0.000,NaN,NaN,23
8,2026-03-28,91,47,69.0,12.5,0,4,0.000,NaN,NaN,19
9,2026-03-29,94,58,76.0,19.4,0,11,0.000,NaN,NaN,26
10,2026-03-30,84,48,66.0,9.3,0,1,0.000,NaN,NaN,16
11,2026-03-31,72,55,63.5,6.8,1,0,0.030,NaN,NaN,14
12,2026-04-01,73,52,62.5,5.7,2,0,0.070,NaN,NaN,13
13,2026-04-02,70,49,59.5,2.6,5,0,0.000,NaN,NaN,10
14,2026-04-03,80,45,62.5,5.5,2,0,0.000,NaN,NaN,13
15,2026-04-04,86,47,66.5,9.4,0,2,0.000,NaN,NaN,17
16,2026-04-05,88,44,66.0,8.8,0,1,0.000,NaN,NaN,16
17,2026-04-06,81,56,68.5,11.2,0,4,0.000,NaN,NaN,19
18,2026-04-07,82,47,64.5,7.1,0,0,0.000,NaN,NaN,15
19,2026-04-08,84,49,66.5,8.9,0,2,0.000,NaN,NaN,17
20,2026-04-09,80,52,66.0,8.3,0,1,0.000,NaN,NaN,16
21,2026-04-10,79,57,68.0,10.2,0,3,0.000,NaN,NaN,18
22,2026-04-11,73,56,64.5,6.5,0,0,0.000,NaN,NaN,15
23,2026-04-12,65,49,57.0,-1.2,8,0,0.050,NaN,NaN,7
24,2026-04-13,65,47,56.0,-2.3,9,0,0.001,NaN,NaN,6
25,2026-04-14,73,40,56.5,-2.0,8,0,0.000,NaN,NaN,7
26,2026-04-15,77,43,60.0,1.3,5,0,0.000,NaN,NaN,10
27,2026-04-16,75,49,62.0,3.1,3,0,0.000,NaN,NaN,12
28,2026-04-17,80,45,62.5,3.4,2,0,0.000,NaN,NaN,13
29,2026-04-18,85,42,63.5,4.2,1,0,0.000,NaN,NaN,14
30,2026-04-19,83,49,66.0,6.5,0,1,0.000,NaN,NaN,16