# Multi-Station Data Retrieval

In this example, we will retrieve multi-station data for the past 30 days from a list of stations:['KLAX', 'KONT', 'KRAL', 'KRIV']

We will then create CSV files of this data and then open that data in Pandas.

## Imports

In [1]:
import pandas as pd
from xmacis2py import get_multi_station_acis_data

In [2]:
# Define our list of station IDs
stations = ['KLAX', 'KONT', 'KRAL', 'KRIV']

## Retrieving The Data With xmACIS2Py

In this example, we want to create CSV files for each station.

To do this we must change our optional argument of `to_csv=True` and in this case it is good practice to set `return_pandas_df=False`

The default path for the CSV files to save is f:XMACIS DATA/{files}

In [3]:
get_multi_station_acis_data(['KLAX', 'KONT', 'KRAL', 'KRIV'],
                      to_csv=True,
                      return_pandas_df=False)

KLAX Data Saved: XMACIS2 DATA/KLAX.csv
KONT Data Saved: XMACIS2 DATA/KONT.csv
KRAL Data Saved: XMACIS2 DATA/KRAL.csv
KRIV Data Saved: XMACIS2 DATA/KRIV.csv

In [4]:
klax = pd.read_csv(f"XMACIS2 DATA/KLAX.csv")

In [5]:
klax

,Date,Maximum Temperature,Minimum Temperature,Average Temperature,Average Temperature Departure,Heating Degree Days,Cooling Degree Days,Precipitation,Snowfall,Snow Depth,Growing Degree Days
0,2026-04-04,87.0,56.0,71.5,11.3,0.0,7.0,0.000,NaN,NaN,22.0
1,2026-04-05,78.0,57.0,67.5,7.2,0.0,3.0,0.000,NaN,NaN,18.0
2,2026-04-06,78.0,61.0,69.5,9.1,0.0,5.0,0.000,NaN,NaN,20.0
3,2026-04-07,70.0,58.0,64.0,3.6,1.0,0.0,0.000,NaN,NaN,14.0
4,2026-04-08,71.0,58.0,64.5,4.0,0.0,0.0,0.000,NaN,NaN,15.0
5,2026-04-09,72.0,60.0,66.0,5.4,0.0,1.0,0.000,NaN,NaN,16.0
6,2026-04-10,67.0,59.0,63.0,2.3,2.0,0.0,0.000,NaN,NaN,13.0
7,2026-04-11,69.0,59.0,64.0,3.3,1.0,0.0,0.001,NaN,NaN,14.0
8,2026-04-12,69.0,58.0,63.5,2.7,1.0,0.0,0.160,NaN,NaN,14.0
9,2026-04-13,66.0,56.0,61.0,0.1,4.0,0.0,0.000,NaN,NaN,11.0
10,2026-04-14,69.0,52.0,60.5,-0.5,4.0,0.0,0.000,NaN,NaN,11.0
11,2026-04-15,70.0,55.0,62.5,1.4,2.0,0.0,0.000,NaN,NaN,13.0
12,2026-04-16,70.0,56.0,63.0,1.8,2.0,0.0,0.000,NaN,NaN,13.0
13,2026-04-17,73.0,56.0,64.5,3.3,0.0,0.0,0.000,NaN,NaN,15.0
14,2026-04-18,76.0,58.0,67.0,5.7,0.0,2.0,0.000,NaN,NaN,17.0
15,2026-04-19,72.0,59.0,65.5,4.1,0.0,1.0,0.000,NaN,NaN,16.0
16,2026-04-20,70.0,56.0,63.0,1.5,2.0,0.0,0.000,NaN,NaN,13.0
17,2026-04-21,70.0,56.0,63.0,1.4,2.0,0.0,0.010,NaN,NaN,13.0
18,2026-04-22,67.0,55.0,61.0,-0.7,4.0,0.0,0.000,NaN,NaN,11.0
19,2026-04-23,72.0,54.0,63.0,1.2,2.0,0.0,0.000,NaN,NaN,13.0
20,2026-04-24,74.0,57.0,65.5,3.6,0.0,1.0,0.000,NaN,NaN,16.0
21,2026-04-25,66.0,55.0,60.5,-1.4,4.0,0.0,0.120,NaN,NaN,11.0
22,2026-04-26,66.0,55.0,60.5,-1.5,4.0,0.0,0.180,NaN,NaN,11.0
23,2026-04-27,66.0,58.0,62.0,-0.1,3.0,0.0,0.000,NaN,NaN,12.0
24,2026-04-28,69.0,53.0,61.0,-1.2,4.0,0.0,0.000,NaN,NaN,11.0
25,2026-04-29,70.0,54.0,62.0,-0.3,3.0,0.0,0.000,NaN,NaN,12.0
26,2026-04-30,70.0,60.0,65.0,2.6,0.0,0.0,0.000,NaN,NaN,15.0
27,2026-05-01,70.0,58.0,64.0,1.5,1.0,0.0,0.000,NaN,NaN,14.0
28,2026-05-02,68.0,58.0,63.0,0.5,2.0,0.0,0.000,NaN,NaN,13.0
29,2026-05-03,67.0,59.0,63.0,0.4,2.0,0.0,0.000,NaN,NaN,13.0
30,2026-05-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
kont = pd.read_csv(f"XMACIS2 DATA/KONT.csv")

In [7]:
kont

,Date,Maximum Temperature,Minimum Temperature,Average Temperature,Average Temperature Departure,Heating Degree Days,Cooling Degree Days,Precipitation,Snowfall,Snow Depth,Growing Degree Days
0,2026-04-04,89.0,63.0,76.0,14.1,0.0,11.0,0.000,NaN,NaN,26.0
1,2026-04-05,88.0,54.0,71.0,9.0,0.0,6.0,0.000,NaN,NaN,21.0
2,2026-04-06,82.0,59.0,70.5,8.4,0.0,6.0,0.000,NaN,NaN,21.0
3,2026-04-07,82.0,56.0,69.0,6.8,0.0,4.0,0.000,NaN,NaN,19.0
4,2026-04-08,83.0,59.0,71.0,8.7,0.0,6.0,0.000,NaN,NaN,21.0
5,2026-04-09,79.0,59.0,69.0,6.6,0.0,4.0,0.000,NaN,NaN,19.0
6,2026-04-10,78.0,57.0,67.5,5.0,0.0,3.0,0.000,NaN,NaN,18.0
7,2026-04-11,74.0,56.0,65.0,2.3,0.0,0.0,0.000,NaN,NaN,15.0
8,2026-04-12,65.0,51.0,58.0,-4.8,7.0,0.0,0.330,NaN,NaN,8.0
9,2026-04-13,66.0,49.0,57.5,-5.4,7.0,0.0,0.010,NaN,NaN,8.0
10,2026-04-14,75.0,49.0,62.0,-1.1,3.0,0.0,0.000,NaN,NaN,12.0
11,2026-04-15,78.0,53.0,65.5,2.3,0.0,1.0,0.000,NaN,NaN,16.0
12,2026-04-16,74.0,55.0,64.5,1.1,0.0,0.0,0.000,NaN,NaN,15.0
13,2026-04-17,80.0,53.0,66.5,3.0,0.0,2.0,0.000,NaN,NaN,17.0
14,2026-04-18,86.0,54.0,70.0,6.3,0.0,5.0,0.000,NaN,NaN,20.0
15,2026-04-19,83.0,59.0,71.0,7.2,0.0,6.0,0.000,NaN,NaN,21.0
16,2026-04-20,80.0,55.0,67.5,3.5,0.0,3.0,0.000,NaN,NaN,18.0
17,2026-04-21,70.0,53.0,61.5,-2.6,3.0,0.0,0.001,NaN,NaN,12.0
18,2026-04-22,72.0,53.0,62.5,-1.8,2.0,0.0,0.000,NaN,NaN,13.0
19,2026-04-23,79.0,51.0,65.0,0.5,0.0,0.0,0.000,NaN,NaN,15.0
20,2026-04-24,77.0,55.0,66.0,1.4,0.0,1.0,0.000,NaN,NaN,16.0
21,2026-04-25,70.0,54.0,62.0,-2.8,3.0,0.0,0.070,NaN,NaN,12.0
22,2026-04-26,67.0,52.0,59.5,-5.5,5.0,0.0,0.020,NaN,NaN,10.0
23,2026-04-27,67.0,53.0,60.0,-5.1,5.0,0.0,0.001,NaN,NaN,10.0
24,2026-04-28,77.0,49.0,63.0,-2.3,2.0,0.0,0.000,NaN,NaN,13.0
25,2026-04-29,79.0,52.0,65.5,0.1,0.0,1.0,0.000,NaN,NaN,16.0
26,2026-04-30,79.0,53.0,66.0,0.4,0.0,1.0,0.000,NaN,NaN,16.0
27,2026-05-01,81.0,57.0,69.0,3.3,0.0,4.0,0.000,NaN,NaN,19.0
28,2026-05-02,82.0,56.0,69.0,3.1,0.0,4.0,0.000,NaN,NaN,19.0
29,2026-05-03,70.0,57.0,63.5,-2.6,1.0,0.0,0.001,NaN,NaN,14.0
30,2026-05-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
kral = pd.read_csv(f"XMACIS2 DATA/KRAL.csv")

In [9]:
kral

,Date,Maximum Temperature,Minimum Temperature,Average Temperature,Average Temperature Departure,Heating Degree Days,Cooling Degree Days,Precipitation,Snowfall,Snow Depth,Growing Degree Days
0,2026-04-04,89.0,54.0,71.5,10.0,0.0,7.0,0.000,NaN,NaN,22.0
1,2026-04-05,90.0,53.0,71.5,9.9,0.0,7.0,0.000,NaN,NaN,22.0
2,2026-04-06,83.0,60.0,71.5,9.8,0.0,7.0,0.001,NaN,NaN,22.0
3,2026-04-07,83.0,53.0,68.0,6.2,0.0,3.0,0.000,NaN,NaN,18.0
4,2026-04-08,85.0,56.0,70.5,8.6,0.0,6.0,0.000,NaN,NaN,21.0
5,2026-04-09,80.0,57.0,68.5,6.5,0.0,4.0,0.000,NaN,NaN,19.0
6,2026-04-10,80.0,58.0,69.0,6.9,0.0,4.0,0.000,NaN,NaN,19.0
7,2026-04-11,75.0,57.0,66.0,3.8,0.0,1.0,0.001,NaN,NaN,16.0
8,2026-04-12,64.0,52.0,58.0,-4.4,7.0,0.0,0.210,NaN,NaN,8.0
9,2026-04-13,67.0,47.0,57.0,-5.5,8.0,0.0,0.020,NaN,NaN,7.0
10,2026-04-14,75.0,47.0,61.0,-1.6,4.0,0.0,0.000,NaN,NaN,11.0
11,2026-04-15,80.0,50.0,65.0,2.2,0.0,0.0,0.000,NaN,NaN,15.0
12,2026-04-16,76.0,53.0,64.5,1.6,0.0,0.0,0.000,NaN,NaN,15.0
13,2026-04-17,82.0,52.0,67.0,4.0,0.0,2.0,0.000,NaN,NaN,17.0
14,2026-04-18,87.0,46.0,66.5,3.3,0.0,2.0,0.000,NaN,NaN,17.0
15,2026-04-19,84.0,57.0,70.5,7.2,0.0,6.0,0.000,NaN,NaN,21.0
16,2026-04-20,81.0,53.0,67.0,3.5,0.0,2.0,0.000,NaN,NaN,17.0
17,2026-04-21,73.0,51.0,62.0,-1.6,3.0,0.0,0.000,NaN,NaN,12.0
18,2026-04-22,74.0,50.0,62.0,-1.8,3.0,0.0,0.000,NaN,NaN,12.0
19,2026-04-23,80.0,48.0,64.0,0.0,1.0,0.0,0.000,NaN,NaN,14.0
20,2026-04-24,78.0,52.0,65.0,0.9,0.0,0.0,0.000,NaN,NaN,15.0
21,2026-04-25,72.0,55.0,63.5,-0.8,1.0,0.0,0.010,NaN,NaN,14.0
22,2026-04-26,67.0,52.0,59.5,-5.0,5.0,0.0,0.300,NaN,NaN,10.0
23,2026-04-27,68.0,52.0,60.0,-4.6,5.0,0.0,0.010,NaN,NaN,10.0
24,2026-04-28,78.0,46.0,62.0,-2.8,3.0,0.0,0.000,NaN,NaN,12.0
25,2026-04-29,81.0,49.0,65.0,0.0,0.0,0.0,0.000,NaN,NaN,15.0
26,2026-04-30,80.0,53.0,66.5,1.4,0.0,2.0,0.000,NaN,NaN,17.0
27,2026-05-01,82.0,55.0,68.5,3.2,0.0,4.0,0.000,NaN,NaN,19.0
28,2026-05-02,83.0,55.0,69.0,3.5,0.0,4.0,0.000,NaN,NaN,19.0
29,2026-05-03,71.0,57.0,64.0,-1.6,1.0,0.0,0.010,NaN,NaN,14.0
30,2026-05-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
kriv = pd.read_csv(f"XMACIS2 DATA/KRIV.csv")

In [11]:
kriv

,Date,Maximum Temperature,Minimum Temperature,Average Temperature,Average Temperature Departure,Heating Degree Days,Cooling Degree Days,Precipitation,Snowfall,Snow Depth,Growing Degree Days
0,2026-04-04,86.0,47.0,66.5,9.4,0.0,2.0,0.000,NaN,NaN,17.0
1,2026-04-05,88.0,44.0,66.0,8.8,0.0,1.0,0.000,NaN,NaN,16.0
2,2026-04-06,81.0,56.0,68.5,11.2,0.0,4.0,0.000,NaN,NaN,19.0
3,2026-04-07,82.0,47.0,64.5,7.1,0.0,0.0,0.000,NaN,NaN,15.0
4,2026-04-08,84.0,49.0,66.5,8.9,0.0,2.0,0.000,NaN,NaN,17.0
5,2026-04-09,80.0,52.0,66.0,8.3,0.0,1.0,0.000,NaN,NaN,16.0
6,2026-04-10,79.0,57.0,68.0,10.2,0.0,3.0,0.000,NaN,NaN,18.0
7,2026-04-11,73.0,56.0,64.5,6.5,0.0,0.0,0.000,NaN,NaN,15.0
8,2026-04-12,65.0,49.0,57.0,-1.2,8.0,0.0,0.050,NaN,NaN,7.0
9,2026-04-13,65.0,47.0,56.0,-2.3,9.0,0.0,0.001,NaN,NaN,6.0
10,2026-04-14,73.0,40.0,56.5,-2.0,8.0,0.0,0.000,NaN,NaN,7.0
11,2026-04-15,77.0,43.0,60.0,1.3,5.0,0.0,0.000,NaN,NaN,10.0
12,2026-04-16,75.0,49.0,62.0,3.1,3.0,0.0,0.000,NaN,NaN,12.0
13,2026-04-17,80.0,45.0,62.5,3.4,2.0,0.0,0.000,NaN,NaN,13.0
14,2026-04-18,85.0,42.0,63.5,4.2,1.0,0.0,0.000,NaN,NaN,14.0
15,2026-04-19,83.0,49.0,66.0,6.5,0.0,1.0,0.000,NaN,NaN,16.0
16,2026-04-20,80.0,46.0,63.0,3.3,2.0,0.0,0.000,NaN,NaN,13.0
17,2026-04-21,73.0,45.0,59.0,-1.0,6.0,0.0,0.000,NaN,NaN,9.0
18,2026-04-22,72.0,43.0,57.5,-2.7,7.0,0.0,0.001,NaN,NaN,8.0
19,2026-04-23,78.0,44.0,61.0,0.6,4.0,0.0,0.000,NaN,NaN,11.0
20,2026-04-24,78.0,48.0,63.0,2.3,2.0,0.0,0.000,NaN,NaN,13.0
21,2026-04-25,68.0,49.0,58.5,-2.4,6.0,0.0,0.010,NaN,NaN,9.0
22,2026-04-26,66.0,48.0,57.0,-4.2,8.0,0.0,0.070,NaN,NaN,7.0
23,2026-04-27,67.0,46.0,56.5,-4.9,8.0,0.0,0.001,NaN,NaN,7.0
24,2026-04-28,77.0,41.0,59.0,-2.7,6.0,0.0,0.000,NaN,NaN,9.0
25,2026-04-29,80.0,44.0,62.0,0.1,3.0,0.0,0.000,NaN,NaN,12.0
26,2026-04-30,78.0,47.0,62.5,0.3,2.0,0.0,0.000,NaN,NaN,13.0
27,2026-05-01,82.0,50.0,66.0,3.6,0.0,1.0,0.000,NaN,NaN,16.0
28,2026-05-02,85.0,51.0,68.0,5.4,0.0,3.0,0.000,NaN,NaN,18.0
29,2026-05-03,71.0,56.0,63.5,0.6,1.0,0.0,0.001,NaN,NaN,14.0
30,2026-05-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN