# Station Meta Data

In these examples, we will download the station meta-data for a single station and a list of stations

## Imports

In [1]:
import pandas as pd
import xmacis2py.data_access as acis_data

In [2]:
# We will use KLAX as our station
station = 'klax'
meta = acis_data.single_station_meta(station)

In [3]:
meta

,Station ID,Station Name,Station Elevation (ft),State,Latitude,Longitude
0,LAX,LOS ANGELES INTL AP,97.0,CA,33.93816,-118.3866

In [4]:
# We will now retrieve a list of station meta-data for a user-defined list of station IDs.
stations = ['KLAX', 'KJFK', 'KDEN', 'KISP']
meta = acis_data.multi_station_meta(stations)

In [5]:
meta

,Station ID,Station Name,Station Elevation (ft),State,Latitude,Longitude
0,LAX,LOS ANGELES INTL AP,97.0,CA,33.93816,-118.38660
1,JFK,JFK INTERNATIONAL AIRPORT,9.0,NY,40.63915,-73.76390
2,DEN,DENVER INTL AP,5404.0,CO,39.84657,-104.65623
3,ISP,ISLIP-LI MACARTHUR AP,83.0,NY,40.79389,-73.10181

In [6]:
# Now Let's try this again and make CSVs for each station
# Default path is f:XMACIS META/{files}
acis_data.multi_station_meta(stations,
                            to_csv=True,
                            return_pandas_df=False)

KLAX.csv saved to XMACIS META
KJFK.csv saved to XMACIS META
KDEN.csv saved to XMACIS META
KISP.csv saved to XMACIS META

In [7]:
# Now let's open the CSVs for each station's meta-data
klax = pd.read_csv(f"XMACIS META/KLAX.csv")

In [8]:
klax

,Station ID,Station Name,Station Elevation (ft),State,Latitude,Longitude
0,LAX,LOS ANGELES INTL AP,97.0,CA,33.93816,-118.3866

In [9]:
kjfk = pd.read_csv(f"XMACIS META/KJFK.csv")

In [10]:
kjfk

,Station ID,Station Name,Station Elevation (ft),State,Latitude,Longitude
0,JFK,JFK INTERNATIONAL AIRPORT,9.0,NY,40.63915,-73.7639

In [11]:
kden = pd.read_csv(f"XMACIS META/KDEN.csv")

In [12]:
kden

,Station ID,Station Name,Station Elevation (ft),State,Latitude,Longitude
0,DEN,DENVER INTL AP,5404.0,CO,39.84657,-104.65623

In [13]:
kisp = pd.read_csv(f"XMACIS META/KISP.csv")

In [14]:
kisp

,Station ID,Station Name,Station Elevation (ft),State,Latitude,Longitude
0,ISP,ISLIP-LI MACARTHUR AP,83.0,NY,40.79389,-73.10181